### ISSUE TITLE
Should we have a separate template for MADA teaching vs. starting new projects?

### ISSUE THREAD

**Issue by wzbillings** [ahgroup/data-analysis-template#10]
Most of the example files in this repo are there for teaching purposes since this repo is also the starting point for projects in Andreas' MADA class. However, when we copy this template to start a new handelgroup research project we really don't need most of those files, and having to delete them is a small inconvenience. it also adds a bunch of random files to the commit history.

Should we have a pared-down repo that doesn't include all of those dummy files for starting "actual" research projects?

**Comment by wzbillings** [comment]
Note that a template for research projects should also include the LICENSE files we agreed on for handelgroup projects, which is absent from this repo.

**Comment by andreashandel** [comment]
prefer to keep a single repo. everyone can adjust as needed.
