### ISSUE TITLE
Multiple CSLs in assets file

### ISSUE THREAD

**Issue by wzbillings** [ahgroup/data-analysis-template#5]
We should decide what the "default" CSL for handelgroup should be -- typically I use American Journal of Epidemiology (aje) style. To ensure consistency across handelgroup projects (since almost all journals have format-free first submissions these days) we should decide which style Andreas wants everyone to use and make sure there's only one CSL in here.

**Comment by andreashandel** [comment]
i want to keep two to show options. switched over to AJE as default.
