### ISSUE TITLE
quarto documents should use quarto standards for YAML headers

### ISSUE THREAD

**Issue by wzbillings** [ahgroup/data-analysis-template#7]
Current quarto documents have the following line in the YAML header.
```
date: "`r Sys.Date()`"
```

This has been superseded by the Quarto format
```
date: last-modified
```
and should be appropriately updated.

Alternatively, this line should be removed from the manuscript since there is typically no reason to include the date in a manuscript.

**Comment by andreashandel** [comment]
updated
