### ISSUE TITLE
How should we format authors and institutions?

### ISSUE THREAD

**Issue by wzbillings** [ahgroup/data-analysis-template#8]
The current manuscript template uses the `author` YAML key to format a single author. Manuscripts typically have many authors and require listing institutions, which is currently not possible in `docx` output for Quarto, or at least very cumbersome.

In most manuscripts, we have manually typed out a list of authors and institutions in the first section of the manuscript. If this is our standardized format for manuscripts that we agree on, the template should be updated.

**Comment by andreashandel** [comment]
template has been updated to look more like our MS setup.
