### ISSUE TITLE
Are many of the README files in this template unnecessary?

### ISSUE THREAD

**Issue by wzbillings** [ahgroup/data-analysis-template#9]
It seems to me that there is probably no need to include, e.g., both a README in the "results" folder and also a README in the "results/figures" folder. Any content that would go in "results/figures/README.md" could go in "results/README.md". Of course we want to have thorough documentation, but overly thorough documentation actually makes the repo contents harder to understand.

If the issue is that we want to ensure those subfolders are cached in github, we should replace, e.g., "results/figures/README.md" with "results/figures/.gitkeep" which would be a dummy file with no contents, but is cached by git. That `.gitkeep` file can then be erased (or not, it doesn't matter since the size will be ~1 byte) when actual contents are added.

**Comment by andreashandel** [comment]
I'll keep all the readme files to signal the importance of detailed documentation. I assume people will adjust (delete) as it makes sense for them. (Also don't want the .gitkeep) to prevent students from being confused by it.
